import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers";
import { AuthLayout, AuthCard } from "@repo/auth";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <AuthLayout>
            <AuthCard src="">
              {children}
            </AuthCard>
          </AuthLayout>
        </body>
      </html>
    </Providers>
  );
}
