export const THEME = {
  MODES: ["dark", "light"],
  SIZES: ["xxs", "xs", "sm", "md", "lg", "xl", "xxl"],
  JUSTIFIES: [
    "normal",
    "start",
    "end",
    "center",
    "between",
    "around",
    "evenly",
    "stretch",
  ],
  ALIGNS: ["start", "end", "center", "base", "stretch"],
  COLORS: [
    "primary",
    "secondary",
    "black",
    "white",
    "danger",
    "warning",
    "info",
    "success",
    "body",
    "shadow",
  ],
  SHADES: [
    "lightest",
    "lighter",
    "light",
    "default",
    "dark",
    "darker",
    "darkest",
  ],
} as const;
