// Generated by Wrangler by running `wrangler --c ./page.wrangler.jsonc types --env-interface CFPageEnv page.env.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface CFPageEnv {
}
