export type IconNames = 
  | "facebook"
  | "linkedin"
  | "twitter"
  | "plus"
  | "file-empty"
  | "dismiss"
  | "dashboard"
  | "administrator"
  | "home"
  | "user-cog"
  | "config"
  | "user-avatar"
  | "stats-bars"
  | "chevron-right"
  | "chevron-up"
  | "chevron-down"
  | "chevron-left"
  | "chevron-sort-down"
  | "chevron-sort-up"
  | "chevron-mini"
  | "more-horizontal"
  | "more-vertical"
  | "hamburger"

